version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:54322"

volumes:
  db:
